apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
  namespace: monitoring-system
data:
  scrape.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'django-cluster-api'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['django-service.default.svc.cluster.local:8000']
