apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: default
  labels:
    app: django-app
spec:
  ports:
  - name: http-metrics
    port: 8000
    targetPort: 8000
  selector:
    app: django-app
