# Generated by Django 6.1 on 2026-08-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='cluster name')),
                ('address', models.CharField(max_length=255, verbose_name='kubernetes API address')),
                ('token', models.TextField(verbose_name='kubernetes access token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
