# Generated by Django 6.1 on 2026-08-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_namespace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Namespace',
        ),
    ]
