# Generated by Django 6.1 on 2026-08-18 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_namespace'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('image', models.CharField(max_length=255)),
                ('replicas', models.IntegerField(default=1)),
                ('cpu_limit', models.CharField(default='500m', max_length=50)),
                ('memory_limit', models.CharField(default='512Mi', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='clusters.namespace')),
            ],
            options={
                'unique_together': {('namespace', 'name')},
            },
        ),
    ]
